version: '3.9'

services:
  database:
    image: library/postgres:14.0-alpine
    container_name: nest-postgres
    ports:
      - '5432:5432'
    networks:
      - backend
    environment:
      POSTGRES_PASSWORD: '0000'
  api:
    build: .
    container_name: nest_api
    ports:
      - '3000:3000'
    depends_on:
      - database
    networks:
      - backend
networks:
  backend:
    driver: bridge
