version: '3.9'

services:
  database:
    image: library/postgres:14.0-alpine
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: '0000'
  api:
    build: .
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - database
volumes:
  postgres_data:
